spring:
  application:
    name: SpringBoot



cars:
  initial-data:
    - id: 1
      model: Slavuta
      producer: ZAZ
      power: 120

    - id: 2
      model: Tavriya
      producer: ZAZ
      power: 110


    - id: 3
      model: Moskvich
      producer: MAZ
      power: 90